# Generated by Django 5.0.2 on 2024-03-18 14:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=255, verbose_name="Email"),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Website"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Settings",
            },
        ),
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_navigation",
                    wagtail.fields.StreamField(
                        [("page", wagtail.blocks.PageChooserBlock())],
                        blank=True,
                        help_text="Main site navigation",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("mastodon", "Mastodon"),
                            ("threads", "Threads"),
                            ("twitter", "Twitter"),
                        ],
                        max_length=255,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="site_settings.socialmediasettings",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "username")},
            },
        ),
    ]
