# Generated by Django 5.0.2 on 2024-04-30 09:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="long_description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="short_description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
