# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: detect-aws-credentials
          - id: detect-private-key
          - id: sort-simple-yaml

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.1
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v4.0.0-alpha.8"
      hooks:
          - id: prettier

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
          - id: pyupgrade

    - repo: https://github.com/adamchainz/django-upgrade
      rev: "1.16.0"
      hooks:
          - id: django-upgrade
            args: [--target-version, "5"]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910-1
      hooks:
          - id: mypy
            additional_dependencies: [types-requests, types-setuptools]
