version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/esterlol_db

    volumes:
      - ./esterlol:/app/esterlol
      - ./pyproject.toml:/app/pyproject.toml
      - ./pdm.lock:/app/pdm.lock

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esterlol_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
