# fly.toml app configuration file generated for ester-lol on 2024-04-29T14:28:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'ester-lol'
primary_region = 'lhr'
console_command = '/app/manage.py shell'

[build]

[deploy]
release_command = 'pdm run python manage.py migrate --noinput'

[env]
PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/app/static'
url_prefix = '/static/'
